name: CLI Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Run CLI tests
        run: pytest tests/test_cli.py
